# recycling the .travis.yml from other project, commented out things
# we don't need ATM but may come handy later -
#before_install:
#  - sudo apt-get update
#  - sudo apt-get --reinstall install -qq language-pack-en language-pack-es

language: python

# For pypy versions, see https://github.com/pyenv/pyenv/tree/master/plugins/python-build/share/python-build
python: 
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  
cache:
  - pip
  - directories:
    - $HOME/.pyenv_cache

env:
    - cocos_utest=1

install:
#  - "pip install -r requirements.txt --use-mirrors"
#  - "pip install . --use-mirrors"
   - python setup.py install
script:
  - cd utest && py.test --tb native
